"""Dataclass DTOs — the API models of stapel-moderation (never ORM rows).

Model-backed DTOs are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); the hand-written
dataclasses here are the envelopes with no single backing model.

The split between :class:`CaseSummaryDTO` and :class:`CaseDetailDTO` is a
dedicated pair, not one shape with fields dropped. A queue page is read
hundreds of times an hour and must not carry complaint text; a case card must.
Building the small one by deleting from the big one is how the day somebody
adds a field to the detail shape becomes the day the queue starts leaking it.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ReportResultDTO:
    """The whole answer to an accepted complaint.

    Carries ``case_ref`` (a short prefix) rather than the case id: the
    reporter needs something to quote at support, not a handle to a resource
    they may not read.
    """

    accepted: bool = True
    report_id: str = ""
    case_ref: str = ""


@dataclass
class ContentDTO:
    """The target's live content, as read at the moment the card was opened.

    ``available`` is explicit so the console can render a ``failed`` branch
    instead of an empty card: a moderator must never decide about content
    nobody showed them.
    """

    available: bool = True
    error: str = ""
    text: str = ""
    title: str = ""
    language: str = ""
    media: List[str] = field(default_factory=list)
    author_id: str = ""
    url: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CasePageDTO:
    """One keyset page of the cross-target queue, plus its continuation."""

    items: List[Any] = field(default_factory=list)
    next_before: Optional[str] = None


@dataclass
class StatsDTO:
    """Queue counters for the console header and DSA Art. 24(1) reporting.

    ``queue_total`` and ``dlq_total`` are separate headline numbers and must
    stay separate in any console that renders them: the first is work a
    MODERATOR owes, the second is work an ENGINEER owes. Adding them together
    is how a broken screening seam spent twelve days on a client stand
    looking like a busy moderation queue.
    """

    by_state: Dict[str, int] = field(default_factory=dict)
    by_target_type: Dict[str, int] = field(default_factory=dict)
    by_severity: Dict[str, int] = field(default_factory=dict)
    open_total: int = 0
    resolved_total: int = 0
    #: Cases a human is expected to work: ``queued`` + ``claimed``.
    queue_total: int = 0
    #: Cases parked because screening kept failing. Not the human queue.
    dlq_total: int = 0
    #: The dead-letter park split by what broke — the DLQ tab's group-by, and
    #: the answer to "which seam do I repair first".
    dlq_by_error_class: Dict[str, int] = field(default_factory=dict)


@dataclass
class PolicyDisclosureDTO:
    """DSA Art. 15(1)(e) — what this deployment actually does, from the code."""

    lang: str = ""
    reasons: List[Dict[str, Any]] = field(default_factory=list)
    rules: List[Dict[str, Any]] = field(default_factory=list)
    automated_means: Dict[str, Any] = field(default_factory=dict)
    human_review: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RescanResultDTO:
    case_id: str
    state: str
    task_id: Optional[str] = None


__all__ = [
    "CasePageDTO",
    "ContentDTO",
    "PolicyDisclosureDTO",
    "ReportResultDTO",
    "RescanResultDTO",
    "StatsDTO",
]
