"""Serializers for the stapel-moderation API.

Model-backed response serializers are generated by the presenters; request
serializers and non-model envelopes live here.

The module-level names resolve the ACTIVE presenter once at import time — a
``STAPEL_SWAP`` override lands in both the emitted schema and the runtime,
because settings are fixed before this module loads.
"""
from __future__ import annotations

from rest_framework import serializers
from stapel_core.django.api.serializers import StapelDataclassSerializer
from stapel_core.django.swappable import get_presenter

from .dto import (
    CasePageDTO,
    ContentDTO,
    PolicyDisclosureDTO,
    ReportResultDTO,
    RescanResultDTO,
    StatsDTO,
)
from .presenters import (
    APPEAL_PRESENTER_KEY,
    CASE_DETAIL_PRESENTER_KEY,
    CASE_PRESENTER_KEY,
    DEFAULT_APPEAL_PRESENTER,
    DEFAULT_CASE_DETAIL_PRESENTER,
    DEFAULT_CASE_PRESENTER,
    DEFAULT_EVENT_PRESENTER,
    DEFAULT_REPORT_PRESENTER,
    DEFAULT_SANCTION_PRESENTER,
    DEFAULT_VERDICT_PRESENTER,
    EVENT_PRESENTER_KEY,
    REPORT_PRESENTER_KEY,
    SANCTION_PRESENTER_KEY,
    VERDICT_PRESENTER_KEY,
)

CaseSerializer = get_presenter(
    CASE_PRESENTER_KEY, default=DEFAULT_CASE_PRESENTER
).serializer_class()
CaseDetailSerializer = get_presenter(
    CASE_DETAIL_PRESENTER_KEY, default=DEFAULT_CASE_DETAIL_PRESENTER
).serializer_class()
ReportSerializer = get_presenter(
    REPORT_PRESENTER_KEY, default=DEFAULT_REPORT_PRESENTER
).serializer_class()
VerdictSerializer = get_presenter(
    VERDICT_PRESENTER_KEY, default=DEFAULT_VERDICT_PRESENTER
).serializer_class()
CaseEventSerializer = get_presenter(
    EVENT_PRESENTER_KEY, default=DEFAULT_EVENT_PRESENTER
).serializer_class()
SanctionSerializer = get_presenter(
    SANCTION_PRESENTER_KEY, default=DEFAULT_SANCTION_PRESENTER
).serializer_class()
AppealSerializer = get_presenter(
    APPEAL_PRESENTER_KEY, default=DEFAULT_APPEAL_PRESENTER
).serializer_class()


# ── Envelope responses ───────────────────────────────────────────────


class ReportResultResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = ReportResultDTO


class ContentResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = ContentDTO


class CasePageResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = CasePageDTO


class StatsResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = StatsDTO


class PolicyDisclosureResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = PolicyDisclosureDTO


class RescanResultResponseSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = RescanResultDTO


# ── Requests ─────────────────────────────────────────────────────────


class ReportCreateSerializer(serializers.Serializer):
    """A complaint (DSA Art. 16(2)).

    ``good_faith`` is the Art. 16(2)(d) declaration and defaults to False:
    a checkbox nobody ticked is a checkbox nobody ticked. Whether
    ``description`` is required depends on the reason's
    ``requires_description``, which is a registry question and is therefore
    answered in the service, not here — and, unlike legacy, an unwanted
    description is never silently erased.
    """

    target_type = serializers.CharField(max_length=64)
    target_key = serializers.CharField(max_length=255)
    reason_code = serializers.CharField(max_length=64)
    description = serializers.CharField(
        required=False, allow_blank=True, default="", max_length=5000
    )
    good_faith = serializers.BooleanField(required=False, default=False)
    contact_email = serializers.EmailField(required=False, allow_blank=True, default="")
    scope_key = serializers.CharField(
        required=False, allow_blank=True, default="", max_length=255
    )


class KeysetQuerySerializer(serializers.Serializer):
    """The paging half every list endpoint shares."""

    before = serializers.DateTimeField(required=False, allow_null=True)
    limit = serializers.IntegerField(required=False, min_value=1, max_value=100)


class CaseQuerySerializer(KeysetQuerySerializer):
    state = serializers.CharField(required=False, allow_blank=True, default="")
    target_type = serializers.CharField(required=False, allow_blank=True, default="")
    reason_code = serializers.CharField(required=False, allow_blank=True, default="")
    scope_key = serializers.CharField(required=False, allow_blank=True, default="")
    severity_min = serializers.IntegerField(required=False, allow_null=True)
    subject_user_id = serializers.UUIDField(required=False, allow_null=True)


class SanctionQuerySerializer(KeysetQuerySerializer):
    subject_user_id = serializers.UUIDField(required=False, allow_null=True)
    state = serializers.CharField(required=False, allow_blank=True, default="")


class AppealQuerySerializer(KeysetQuerySerializer):
    state = serializers.CharField(required=False, allow_blank=True, default="")


class PolicyQuerySerializer(serializers.Serializer):
    lang = serializers.CharField(required=False, allow_blank=True, default="")
    target_type = serializers.CharField(required=False, allow_blank=True, default="")


class SanctionRequestSerializer(serializers.Serializer):
    """The optional sanction attached to a verdict."""

    kind = serializers.CharField(max_length=24)
    duration_seconds = serializers.IntegerField(required=False, allow_null=True, min_value=1)
    scope = serializers.CharField(required=False, allow_blank=True, default="*", max_length=255)
    reason_code = serializers.CharField(required=False, allow_blank=True, default="", max_length=64)
    note = serializers.CharField(required=False, allow_blank=True, default="", max_length=5000)


class VerdictRequestSerializer(serializers.Serializer):
    """A moderator's decision, optionally with the consequence in one act.

    "Take it down AND suspend the seller AND tell them why" is one button in
    the console and one transaction here; legacy needed three screens and
    recorded two of them nowhere.
    """

    decision = serializers.CharField(max_length=16)
    reason_code = serializers.CharField(required=False, allow_blank=True, default="", max_length=64)
    note = serializers.CharField(required=False, allow_blank=True, default="", max_length=5000)
    sanction = SanctionRequestSerializer(required=False, allow_null=True)


class SanctionCreateSerializer(serializers.Serializer):
    """A sanction issued on its own, outside a verdict.

    ``case_id`` is optional in the request and mandatory in the model: when
    it is absent the service opens a ``manual`` case so the sanction still
    has exactly one audit trail behind it.
    """

    subject_user_id = serializers.UUIDField()
    kind = serializers.CharField(max_length=24)
    reason_code = serializers.CharField(required=False, allow_blank=True, default="", max_length=64)
    note = serializers.CharField(required=False, allow_blank=True, default="", max_length=5000)
    duration_seconds = serializers.IntegerField(required=False, allow_null=True, min_value=1)
    scope = serializers.CharField(required=False, allow_blank=True, default="*", max_length=255)
    case_id = serializers.UUIDField(required=False, allow_null=True)
    target_type = serializers.CharField(required=False, allow_blank=True, default="", max_length=64)
    target_key = serializers.CharField(required=False, allow_blank=True, default="", max_length=255)


class SanctionLiftSerializer(serializers.Serializer):
    note = serializers.CharField(required=False, allow_blank=True, default="", max_length=5000)


class AppealCreateSerializer(serializers.Serializer):
    case_id = serializers.UUIDField()
    body = serializers.CharField(max_length=10000)
    sanction_id = serializers.UUIDField(required=False, allow_null=True)


class AppealResolveSerializer(serializers.Serializer):
    outcome = serializers.CharField(max_length=16)
    note = serializers.CharField(required=False, allow_blank=True, default="", max_length=5000)
    reason_code = serializers.CharField(required=False, allow_blank=True, default="", max_length=64)


__all__ = [
    "AppealCreateSerializer",
    "AppealQuerySerializer",
    "AppealResolveSerializer",
    "AppealSerializer",
    "CaseDetailSerializer",
    "CaseEventSerializer",
    "CasePageResponseSerializer",
    "CaseQuerySerializer",
    "CaseSerializer",
    "ContentResponseSerializer",
    "KeysetQuerySerializer",
    "PolicyDisclosureResponseSerializer",
    "PolicyQuerySerializer",
    "ReportCreateSerializer",
    "ReportResultResponseSerializer",
    "ReportSerializer",
    "RescanResultResponseSerializer",
    "SanctionCreateSerializer",
    "SanctionLiftSerializer",
    "SanctionQuerySerializer",
    "SanctionRequestSerializer",
    "SanctionSerializer",
    "StatsResponseSerializer",
    "VerdictRequestSerializer",
    "VerdictSerializer",
]
