# Generated by Django 6.0.7 on 2026-08-21 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_key', models.CharField(db_index=True, max_length=255)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('origin', models.CharField(choices=[('submission', 'Target submitted for review'), ('report', 'User report'), ('manual', 'Opened by a moderator'), ('rescan', 'Re-screen of an earlier decision'), ('appeal', 'Reopened by an appeal')], default='report', max_length=16)),
                ('state', models.CharField(choices=[('open', 'Open'), ('screening', 'Screening'), ('queued', 'Queued'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('severity', models.SmallIntegerField(default=0)),
                ('subject_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('first_reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.UUIDField(blank=True, null=True)),
                ('claimed_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('screen_task_id', models.UUIDField(blank=True, null=True)),
                ('screen_attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'moderation_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSanctionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('projection_seq', models.BigIntegerField(default=0)),
                ('projection_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('projection_updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
                ('sanctions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'moderation_user_sanction_state',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_user_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('content_removed', 'Content removed'), ('posting_restricted', 'Posting restricted'), ('suspended', 'Suspended'), ('banned', 'Banned')], max_length=24)),
                ('scope', models.CharField(default='*', max_length=255)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lifted', 'Lifted'), ('overturned', 'Overturned')], default='active', max_length=16)),
                ('issued_by', models.UUIDField(blank=True, null=True)),
                ('lifted_by', models.UUIDField(blank=True, null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='moderation.case')),
            ],
            options={
                'db_table': 'moderation_sanction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appellant_id', models.UUIDField(db_index=True)),
                ('body', models.TextField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('upheld', 'Upheld (the original decision stands)'), ('overturned', 'Overturned'), ('withdrawn', 'Withdrawn')], db_index=True, default='open', max_length=16)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='moderation.case')),
                ('sanction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='moderation.sanction')),
            ],
            options={
                'db_table': 'moderation_appeal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs review'), ('dismissed', 'Dismissed')], max_length=16)),
                ('source', models.CharField(choices=[('llm', 'LLM screener'), ('rule', 'Deterministic rule'), ('human', 'Human moderator'), ('policy_default', 'Policy default'), ('appeal', 'Appeal outcome')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='moderation.case')),
            ],
            options={
                'db_table': 'moderation_verdict',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='last_verdict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moderation.verdict'),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('reported', 'Reported'), ('resubmitted', 'Resubmitted'), ('screen_started', 'Screening started'), ('screen_failed', 'Screening failed'), ('verdict', 'Verdict recorded'), ('state_changed', 'State changed'), ('applied', 'Verdict applied by the target'), ('apply_failed', 'Verdict application unconfirmed'), ('claimed', 'Claimed'), ('released', 'Released'), ('sanctioned', 'Sanction issued'), ('appealed', 'Appealed'), ('reopened', 'Reopened'), ('notified', 'Notification requested')], max_length=24)),
                ('from_state', models.CharField(blank=True, choices=[('open', 'Open'), ('screening', 'Screening'), ('queued', 'Queued'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='', max_length=16)),
                ('to_state', models.CharField(blank=True, choices=[('open', 'Open'), ('screening', 'Screening'), ('queued', 'Queued'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='moderation.case')),
            ],
            options={
                'db_table': 'moderation_case_event',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='mod_event_case')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=64)),
                ('target_key', models.CharField(max_length=255)),
                ('reporter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason_code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('good_faith', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='moderation.case')),
            ],
            options={
                'db_table': 'moderation_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='mod_report_case'), models.Index(fields=['reason_code'], name='mod_report_reason')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_key', 'reporter_id'), name='uniq_report_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['subject_user_id', 'state', 'expires_at'], name='mod_sanction_lookup'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('case', 'appellant_id'), name='uniq_appeal_per_case_user'),
        ),
        migrations.AddIndex(
            model_name='verdict',
            index=models.Index(fields=['case', '-created_at'], name='mod_verdict_case'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['state', 'severity', '-created_at'], name='mod_case_queue'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['target_type', 'state'], name='mod_case_target'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['subject_user_id', '-created_at'], name='mod_case_subject'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('open', 'screening', 'queued', 'claimed'))), fields=('target_type', 'target_key'), name='uniq_open_case_per_target'),
        ),
    ]
