# Generated by Django 6.0.7 on 2026-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
