# Generated by Django 6.0.7 on 2026-09-02 23:07

"""CaseOrigin gains "draft": a refusal recorded before anything was
published (services.screen_draft). Choices only — no column changes, no
data rewrite, and nothing to contract later.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_report_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='origin',
            field=models.CharField(choices=[('submission', 'Target submitted for review'), ('report', 'User report'), ('manual', 'Opened by a moderator'), ('rescan', 'Re-screen of an earlier decision'), ('appeal', 'Reopened by an appeal'), ('draft', 'Refused at the draft step')], default='report', max_length=16),
        ),
    ]
