# Generated by Django 6.0.8 on 2026-09-03 07:43

"""Four columns that let a stuck case be recovered instead of forgotten.

``last_screened_at`` / ``resubmitted_at`` are a pair: an edit that lands
after the last screening is what ``tasks.rescreen_stuck_cases`` reads to
decide an edit must be looked at again. ``rescreen_attempts`` is the backoff
exponent and the give-up counter in one number, and ``escalated_at`` is the
field a queue filter sorts on when the machine has spent its cap — set once,
never a decision, and never a substitute for a human verdict.

Additive and nullable throughout: every existing case reads as "never
re-screened, never resubmitted", which is exactly true of the 51 that were
parked on the stand when this was written.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_case_origin_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='escalated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rescreen_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('reported', 'Reported'), ('resubmitted', 'Resubmitted'), ('screen_started', 'Screening started'), ('screen_failed', 'Screening failed'), ('verdict', 'Verdict recorded'), ('state_changed', 'State changed'), ('applied', 'Verdict applied by the target'), ('apply_failed', 'Verdict application unconfirmed'), ('claimed', 'Claimed'), ('released', 'Released'), ('sanctioned', 'Sanction issued'), ('appealed', 'Appealed'), ('reopened', 'Reopened'), ('notified', 'Notification requested'), ('rescreened', 'Re-screened by the stuck sweep'), ('escalated', 'Given up on by the machine, left for a human')], max_length=24),
        ),
    ]
