# Generated by Django 6.0.8 on 2026-09-06

"""The idempotency constraint learns about the dead-letter park.

``uniq_open_case_per_target`` is the whole idempotency mechanism: one open
case per target, so a redelivered intake event finds the existing row
instead of opening a twin. ``dlq`` joins ``OPEN_STATES`` because a
dead-lettered case is still THE case for its target — letting a redelivery
open a second one beside it would turn one broken seam into two rows nobody
can reconcile.

Postgres rebuilds a partial unique index here. On a live table that is a
brief exclusive lock on ``moderation_case``; drop-then-create rather than
create-concurrently because the pair must not be observable apart, and
because the window where NO constraint exists is a window where a
redelivery could write the twin this constraint exists to prevent. Run it
with the screening workers stopped, or accept a few seconds of write
blocking on a table whose write rate is a moderation queue's.

The ``choices`` edits are cosmetic — Django re-renders the state and audit
vocabularies into the column definition, and neither column's storage
changes.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_case_dead_letter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='case',
            name='uniq_open_case_per_target',
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='from_state',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('screening', 'Screening'), ('queued', 'Queued'), ('claimed', 'Claimed'), ('dlq', 'Dead-lettered'), ('resolved', 'Resolved')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('reported', 'Reported'), ('resubmitted', 'Resubmitted'), ('screen_started', 'Screening started'), ('screen_failed', 'Screening failed'), ('verdict', 'Verdict recorded'), ('state_changed', 'State changed'), ('applied', 'Verdict applied by the target'), ('apply_failed', 'Verdict application unconfirmed'), ('claimed', 'Claimed'), ('released', 'Released'), ('sanctioned', 'Sanction issued'), ('appealed', 'Appealed'), ('reopened', 'Reopened'), ('notified', 'Notification requested'), ('rescreened', 'Re-screened by the stuck sweep'), ('escalated', 'Given up on by the machine, left for a human'), ('dead_lettered', 'Parked: the screening seam kept failing'), ('revived', 'Taken back out of the dead-letter park')], max_length=24),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='to_state',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('screening', 'Screening'), ('queued', 'Queued'), ('claimed', 'Claimed'), ('dlq', 'Dead-lettered'), ('resolved', 'Resolved')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('open', 'screening', 'queued', 'claimed', 'dlq'))), fields=('target_type', 'target_key'), name='uniq_open_case_per_target'),
        ),
    ]
